[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "sklearn",
    "numpy",
    "pandas",
    "keras",
    "tensorflow",
    "tensorflow_probability"
]
build-backend = "setuptools.build_meta"
